### ISSUE TITLE
create dialog elements

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-gpsTracker#1]
Create dialog elements in the style of picture below. Separate elements are:

* device
* direction arrow (pointing straight up by default)
* some kind of reception indicator (satellite dish with reception bars?)

![](https://cloud.githubusercontent.com/assets/16549968/25392836/0cba6f14-29da-11e7-9c12-741828782382.jpg)

**Comment by nomisum** [comment]
reception indicator needs how many states? ON/OFF or 0-1-2-3?

**Comment by McDiod** [comment]
0-1-2-3 would be cool

**Comment by McDiod** [comment]
Also I need some room for distance (the  "--- yd" in the picture) and time of day ("3:45p" in the picture). Time isn't a must though.
